### ISSUE TITLE
Type hint: TreeBuilder does not released.

### ISSUE THREAD

**Issue by jeferson-guedes** [php-bundles/json-request-bundle#15]
Looking at the code I saw that it was even merged but a new tag was not generated, see PR: https://github.com/symfony-bundles/json-request-bundle/pull/14

Method "Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder()" might add "TreeBuilder" as a native return type declaration in the future. Do the same in implementation "SymfonyBundles\JsonRequestBundle\DependencyInjection\Configuration" now to avoid errors or add an explicit @return annotation to suppress this message.

**Comment by jeferson-guedes** [comment]
@beesofts

**Comment by beesofts** [comment]
I don't have right to add a tag, can anyone help ?

**Comment by khaperets** [comment]
Pushed new tag 4.1.2
