### ISSUE TITLE
getContentType method is deprecated as of Symfony 6.2

### ISSUE THREAD

**Issue by dannyvankooten** [php-bundles/json-request-bundle#18]
```
User Deprecated: Since symfony/http-foundation 6.2: The \"Symfony\\Component\\HttpFoundation\\Request::getContentType()\" method is deprecated, use \"getContentTypeFormat()\" instead.
```

**Comment by kanopia** [comment]
any news about this?

**Comment by frandzdy** [comment]
Hey,

We need that to be update 

` Root composer.json requires symfony-bundles/json-request-bundle ^4.1.2 -> satisfiable by symfony-bundles/json-request-bundle[4.1.2].
    - symfony-bundles/json-request-bundle 4.1.2 requires symfony/framework-bundle ^4.3 || ^5.0 || ^6.0 -> found symfony/framework-bundle[v4.3.0, ..., v4.4.51, v5.0.0, ..., v5.4.36, v6.0.0, ..., v6.4.4] but it conflicts with your root composer.json require (^7.0).
`
We need that to update to symfony 7.

Thanks

**Comment by Misosooup** [comment]
same here, need this to be updated.

**Comment by dannyvankooten** [comment]
I have an open pull request for this in #19, but someone with commit rights will have to approve it in order to be merged. 

Personally, I would just dump the [single event listener](https://github.com/php-bundles/json-request-bundle/blob/master/src/EventListener/RequestTransformerListener.php) in your application directly, fix the deprecation notice and then get rid of the dependency on this package.
