### ISSUE TITLE
Possibility to parse ld+json

### ISSUE THREAD

**Issue by gassan** [php-bundles/json-request-bundle#5]
Api Platform sends request in json+ld content type. it would be nice to parse those requests too.
<img width="676" alt="Screenshot 2021-05-06 at 19 43 41" src="https://user-images.githubusercontent.com/2382015/117342659-c3094900-aea3-11eb-9a62-8452164db0c8.png">

**Comment by mehdibo** [comment]
@khaperets is this a desired feature? I can submit a PR if it is

**Comment by gassan** [comment]
Why not to make expected  request types configurable with `['json']` as default value?

**Comment by mehdibo** [comment]
In my opinion, that's an overkill, if it can handle both that would be perfect, `json+ld` is basically json so I don't see no harm in parsing it too
